horiuchi/dtsgenerator

gulpfile.js
lib/cli.ts
tsd.json
typings/asyncblock/asyncblock.d.ts
typings/tsd.d.ts

implement input source of stdin

---

.editorconfig
src/cli.ts
src/generator.ts
src/index.ts
src/model.ts
src/process.ts
src/utils.ts
test/error_case_test.ts
test/expected_file/apimeta.d.ts
test/expected_file/news.d.ts
test/expected_file/schema.d.ts
test/file_schema_test.ts
test/simple_schema_test.ts
tsconfig.json

remove default interface prefix: e.g. 'I'
And add prefix optional parameter.

add `prefix` boot parameter

---

dtsm.json
schema/news.json
src/cli.ts
src/generator.ts
src/jsonschema.d.ts
src/utils.ts
test/expected_file/apimeta.d.ts
test/expected_file/schema.d.ts
test/file_schema_test.ts
test/simple_schema_test.ts
typings/bundle.d.ts
typings/es6-collections/es6-collections.d.ts

Support union type

---

schema/circular.json
src/typeDefenition.ts
src/utils.ts
src/writeProcessor.ts
test/error_case_test.ts
test/expected_file/circular.d.ts
test/file_schema_test.ts
tsconfig.json

Add checking circular references

---

src/cli.ts
src/index.ts
src/jsonSchemaParser.ts
src/jsonschema.d.ts
src/typeDefinition.ts
src/utils.ts
src/writeProcessor.ts
test/error_case_test.ts
test/simple_schema_test.ts

feat: import example property code from PR

---

src/cli.ts
src/index.ts
src/jsonSchemaParser.ts
src/schemaid.ts
src/typeDefinition.ts
src/utils.ts
test/expected_file/schema.d.ts

feat: remove `isInnerType` property

---

schema/advanced_example.json
schema/news.json
src/cli.ts
src/index.ts
src/jsonSchemaParser.ts
src/jsonschema.d.ts
src/schemaid.ts
src/typeDefinition.ts
src/utils.ts
src/writeProcessor.ts
test/error_case_test.ts
test/expected_file/advanced_schema.d.ts
test/expected_file/circular.d.ts
test/expected_file/news.d.ts
test/expected_file/schema.d.ts
test/expected_file/simple_schema.d.ts
test/file_schema_test.ts
test/schemaid_test.ts
test/simple_schema_test.ts
tsconfig.json

Supported `defenitions` sub nodes type.

Support openapi

---

src/writeProcessor.ts

Fix crash for non string example

---

README.md
package.json
src/cli.ts
src/commandOptions.ts
src/index.ts
src/jsonSchemaParser.ts
src/schemaid.ts
src/typeDefinition.ts
src/utils.ts
src/writeProcessor.ts
test/commandOptions_test.ts
test/error_case_test.ts
test/expected_file/news.d.ts
test/file_schema_test.ts
test/simple_schema_test.ts
tsconfig.json
tslint.json

Support new options

---

src/commandOptions.ts
src/utils.ts
test/simple_schema_test.ts

#225 #226  #227 
@dawidgarus @philliphoff 
Thank you for yours contribution! 👍 
I merged yours changing and cleaned up code.

fix: Create deep copy of schemes from allOf when they are merged

---

src/writeProcessor.ts
test/simple_schema_test.ts

Add unit test pattern for #222

Update PR #222

---

src/writeProcessor.ts

It will work with typescript compiler, and most editor/IDE supports UTF-8 (but not all, some will display a "invalid char").
#221

insert Unicode "Zero Width Space" to prevent error

---

package-lock.json
package.json
src/cli.ts
src/commandOptions.ts
src/core/index.ts
src/core/schemaConvertor.ts
src/core/utils.ts
test/commandOptions_test.ts
test/simple_schema_test.ts

remove `--target` and `--header` options.

Remove unused command line options

---

.gitignore
bin/dtsgen
example/add-prefix/index.ts
example/add-prefix/package-lock.json
example/add-prefix/package.json
example/add-prefix/tsconfig.json
example/tsconfig.json
package-lock.json
package.json
src/cli.ts
src/commandOptions.ts
src/core/dtsGenerator.ts
src/core/index.ts
src/core/jsonSchema.ts
src/core/referenceResolver.ts
src/core/schemaConvertor.ts
src/core/schemaId.ts
src/core/typeNameConvertor.ts
src/core/utils.ts
src/core/writeProcessor.ts
test/commandOptions_test.ts
test/core/schemaId_test.ts
test/simple_schema_test.ts
tsconfig-build.json
tsconfig.json

For customizing namespace and interface name.

Add lib interface

---

README.md
SupportedFeatures.md
package.json
src/core/dtsGenerator.ts
src/core/schemaConvertor.ts
test/simple_schema_test.ts
test/snapshots/json-schema-draft-04/circular-ref/_expected.d.ts
test/snapshots/json-schema-draft-04/news/_expected.d.ts
test/snapshots/json-schema-draft-04/simple-example/_expected.d.ts
test/snapshots/json-schema-draft-07/schema/_expected.d.ts
test/snapshots/json-schema-draft-07/simple-example/_expected.d.ts
test/snapshots/openapi-v2/schema/_expected.d.ts

Add supported features document

---

.gitignore

Need add .vscode/ to .gitignore

added  .vscode/ to .gitignore

---

src/core/dtsGenerator.ts
src/jsonPointer.ts
test/simple_schema_test.ts

Support the property name including `/`

---

src/core/referenceResolver.ts
test/error_case_test.ts
test/snapshots/openapi-v3/group-sample/_expected.d.ts
test/snapshots/openapi-v3/group-sample/group_openapi.json

fix: the bug of $ref target not exists on OpenAPI schema

---

src/core/jsonSchema.ts

Support ref objects for OAS3 requestBodies + responses

---

SupportedFeatures.md
src/core/jsonSchema.ts

Support the application/x-www-form-urlencoded mime type

---

src/core/typeNameConvertor.ts

fix: the last character was not cleaned

---

src/core/dtsGenerator.ts
test/tuple_test.ts

Improve tuple type output

---

src/core/jsonSchema.ts
test/snapshots/openapi-v3/support-media-type/_expected.d.ts
test/snapshots/openapi-v3/support-media-type/example.yaml

Support dynamic json media type

---

src/core/jsonSchema.ts
test/snapshots/openapi-v3/support-media-type/_expected.d.ts
test/snapshots/openapi-v3/support-media-type/example.yaml

fix: the bug of the specific identifier

---

src/core/schemaId.ts

Wrong typescript import statement in src/core/schemaId.ts (produces TS error) -> fixed

Fix TS import statement

---

src/core/schemaConvertor.ts
test/simple_schema_test.ts
test/snapshots/json-schema-draft-04/apimeta/_expected.d.ts
test/snapshots/openapi-v3/empty_response/_expected.d.ts
test/snapshots/openapi-v3/empty_response/empty_response.yaml
test/snapshots/openapi-v3/petstore-no-namespace/_expected.d.ts

fix: the bug of implementation of #386

---

SupportedFeatures.md
src/core/jsonSchema.ts
test/snapshots/openapi-v3/support-media-type/_expected.d.ts
test/snapshots/openapi-v3/support-media-type/example.yaml

- text/plain and text/html media types will generate string types.

add text media types

---

package.json
src/core/schemaId.ts
test/simple_schema_test.ts

fix issue #407

---

src/commandOptions.ts
test/commandOptions_test.ts

fix command example

---

README.md
src/cli.ts
src/commandOptions.ts
test/commandOptions_test.ts

Omit load config error on not config option

---

SupportedFeatures.md
src/core/jsonSchema.ts
test/snapshots/openapi-v3/support-media-type/_expected.d.ts
test/snapshots/openapi-v3/support-media-type/example.yaml

Hello,
This PR add support for media type application/octet-stream is commonly used for upload / download endpoints.
see #430 issue for more details

feat: add support for application/octet-stream media type

---

src/core/astBuilder.ts
src/core/dtsGenerator.ts
test/simple_schema_test.ts
test/snapshots/json-schema-draft-04/openapi-v2.0/_expected.d.ts
test/snapshots/json-schema-draft-04/openapi-v3.0/_expected.d.ts
test/snapshots/openapi-v2/schema/_expected.d.ts

Fixes https://github.com/horiuchi/dtsgenerator/issues/435#issuecomment-664946922

feat: add support for patternProperties

---

src/core/dtsGenerator.ts
src/core/jsonSchema.ts
src/core/utils.ts
test/simple_schema_test.ts
test/snapshots/openapi-v2/inherited-def/_expected.d.ts
test/snapshots/openapi-v2/inherited-def/schema.yaml

Fix inherited type on allof

---

src/core/dtsGenerator.ts
test/nested_allof_test.ts

fix: allOf bug

---

SupportedFeatures.md
src/core/jsonSchema.ts
test/snapshots/openapi-v3/support-media-type/_expected.d.ts
test/snapshots/openapi-v3/support-media-type/example.yaml

feat: multipart support

---

README.md
src/core/index.ts
test/config_test.ts

feat: add support for passing config object with NodeJS API usage

---

src/core/config.ts

fix: using package without esModuleInterop

---

src/core/astBuilder.ts
src/core/dtsGenerator.ts
test/simple_schema_test.ts

Add to support the null type enum value for #457

---

src/core/type.ts

for https://github.com/horiuchi/dtsgenerator/issues/453#issuecomment-747516578

export ts for plugin

---

src/core/dtsGenerator.ts
test/simple_schema_test.ts
test/snapshots/json-schema-draft-04/advanced-example/_expected.d.ts
test/snapshots/json-schema-draft-07/advanced-example/_expected.d.ts

Improve the type result of oneOf/anyOf property

---

SupportedFeatures.md
src/core/astBuilder.ts
src/core/dtsGenerator.ts
test/array_test.ts
test/tuple_test.ts

Feature: support for `additionalItems`

---

src/core/dtsGenerator.ts

fix: update `generate` function to use recommended immutable approach for typescript transforms

---

src/core/astBuilder.ts
src/core/dtsGenerator.ts
test/simple_schema_test.ts
test/snapshots/json-schema-draft-04/openapi-v3.0/_expected.d.ts
test/snapshots/json-schema-draft-07/complex-patterns/_expected.d.ts
test/snapshots/openapi-v2/inherited-def/_expected.d.ts
test/snapshots/openapi-v3/group-sample/_expected.d.ts

improvement: support freeform objects w/ index signature instead of `unknown` keyword

---

SupportedFeatures.md
src/core/jsonSchema.ts
test/snapshots/openapi-v3/support-media-type/_expected.d.ts
test/snapshots/openapi-v3/support-media-type/example.yaml

Support parameters with content

---

src/core/jsonSchema.ts
src/core/openApiV2.ts
src/core/utils.ts
test/simple_schema_test.ts
test/snapshots/openapi-v2/petstore-json/_expected.d.ts
test/snapshots/openapi-v2/petstore/_expected.d.ts

Fixed #496
And improve the support of parameter object property.

Support `file` type

---

package-lock.json
package.json
src/core/jsonSchema.ts
src/core/type.ts

Support new schema type without new features

---

README.md

Just noticed this while reading docs, figured I'd offer a quick fix.

Fix minor spelling error in README.md
