README.md
lib/cli.ts
package.json

This PR makes it possible to use patterns to set the schema files
`bin/dtsgen -o types.d.ts schema/**/*.schema.json`

add support for schema patterns with glob

---

lib/generator.ts

- Fix a bug on null property
- Make draft03 "required" work in some way. Is not possible to have it supporte ts optional ? attribute, cause required default is different between draft03/04 but at least it generate the d.ts also on draft03,
without the ?. Better than nothing. 
What do you think about it? Why not integrate it?
Of course I can't update to draft 04 my sources...

Support draft03 generation

---

lib/generator.ts

Currently:
```
{
"FooList": {
"type": "array",
"items": {
"$ref": "#/definitions/Foo"
}
}
```
=> `export interface IFooList extends Array<I/definitions/Foo#>`
Expected:
`export interface IFooList extends Array<IFoo>`

Fix: resolve reference in `extends Array<T>`

---

package.json
src/jsonSchemaParser.ts

Ironically, I find YAML far superior for creating JSON-schema for it's relative ease of reading and editing.   This PR adds support for YAML input files by using the safeLoad method of [`js-yaml`](https://www.npmjs.com/package/js-yaml) package to load files ending in '.yaml'.

Added support for YAML input files.

---

src/utils.ts

Prints error as JSON instead of just `[object Object]`.
Before:
```
debugSource=[object Object]
Error: unknown type: /size
```
After:
```
debugSource={
"description": "Size in pixels of the image",
"type": "/size"
}
Error: unknown type: /size
```
/cc @jasonreisman

Improve message in error log

---

src/utils.ts
test/simple_schema_test.ts

Currently, when many schema is used multiple times in different allOf, it gets mutated each time.
Example schema:
```js
{
definitions: {
Parent: {
type: 'object',
properties: {
parent: {
type: 'string',
},
},
},
FirstChild: {
allOf: [
{ $ref: '#/definitions/Parent' },
{
type: 'object',
properties: {
first: {
type: 'string',
},
},
},
],
},
SecondChild: {
allOf: [
{ $ref: '#/definitions/Parent' },
{
type: 'object',
properties: {
second: {
type: 'string',
},
},
},
],
},
},
}
```
Generated d.ts:
```ts
declare namespace Definitions {
export interface FirstChild {
parent?: string;
first?: string;
}
export interface Parent {
parent?: string;
first?: string;
}
export interface SecondChild {
parent?: string;
first?: string;
second?: string;
}
}
```
But the generated d.ts should be:
```ts
declare …
```

fix: Create deep copy of schemes from allOf when they are merged

---

src/typeDefinition.ts
test/simple_schema_test.ts
test/tuple_test.ts

This commit adds minItems and maxItems support for array tuples and breaks out tests for tuples to their own module.
Adopting this change will change the effective typings of tuples as compared to the prior commit. In particular, I believe the prior implementation was incorrect, in that it did not allow for extra elements to appear (i.e. what should have been unbounded wasn't).
Under this commit, tuples don't automagically become bounded at the number of items in the schema, but rather their length is determined by minItems and maxItems.
`any` at the end of an array literal results in such an array that goes to ...any[] at the end.
`Object` binds to everything except the absence of anything -- i.e.
`x: [ Object ] = [ undefined ]` is legitimate, thus making Object the right choice to …

feat: minItems, maxItems for array tuples

---

src/typeDefinition.ts
test/tuple_test.ts

This commit fixes two problems in 2936a812f :
1. `[]` is not a valid tuple and shouldn't have been included in the unions.
It's thus removed.
2. `maxItems` didn't work as intended, and so is removed.

fix: remove maxItems, empty tuples

---

src/typeDefinition.ts
test/tuple_test.ts

If `items.length === 0 && minItems !== undefined`, yield tuples sufficient
to fill out minItems, e.g. if `minItems === 2`, yield `[Object, Object] | [Object, Object, any]`.
If `items.length === 0 && minItems === undefined`, yield `any[]`.

fix: items.length === 0 cases in tuples

---

src/typeDefinition.ts
test/simple_schema_test.ts

Please consider following example:
```
Parent
properties:
parent
FirstChild
allOf:
- $ref: SecondChild.yaml
properties:
first
SecondChild
allOf:
- $ref: Parent.yaml
properties:
second
```
Current output model for this example is:
```
declare namespace Definitions {
export interface FirstChild {
first?: string;
}
..
}
```
Correct output should be:
```
declare namespace Definitions {
export interface FirstChild {
parent?: string;
second?: string;
first?: string;
}
..
}
```
During traversing definitions of types they are sorted alphabetically: 
```
jsonSchemaParser.ts:80     const keys = Object.keys(env).sort();
```
In our example the `FirstChild` will be the first type to walk through by the processor.
When `FirstChild` schema is merged with its $ref: `SecondChild` schema, target properties …

fix: missing properties in models from unresolved $refs

---

src/core/jsonSchema.ts
src/core/schemaConvertor.ts
test/snapshots/openapi-v2/petstore-json/_expected.d.ts
test/snapshots/openapi-v2/petstore/_expected.d.ts
test/snapshots/openapi-v3/petstore-change-namespace/_expected.d.ts
test/snapshots/openapi-v3/petstore-no-namespace/_expected.d.ts
test/snapshots/openapi-v3/petstore-no-operation-id/_expected.d.ts
test/snapshots/openapi-v3/petstore-no-operation-id/petstore-expanded.yaml
test/snapshots/openapi-v3/petstore/_expected.d.ts

Apply feedback for 304

---

src/core/jsonSchema.ts
test/snapshot_test.ts
test/snapshots/openapi-v3/yaml-reference/_expected.d.ts
test/snapshots/openapi-v3/yaml-reference/yaml-reference.yaml
tsconfig.json

js-yaml apparently re-uses objects that are defined using the yaml reference
syntax. This causes dtsgenerator to miss generating the schema and subsequently
causes an error when looking for that schema.

fix missing schema due to yaml references

---

src/core/dtsGenerator.ts
src/core/jsonSchemaDraft04.d.ts
src/core/jsonSchemaDraft07.d.ts
test/snapshots/openapi-v3/nullable/_expected.d.ts
test/snapshots/openapi-v3/nullable/nullable.yaml
tsconfig.json

typescript considers
field?: number
to be different from
field?: number | null
It seems that dtsgenerator allows using 'null' and so its possible to create a nullable type with oneOf. However openapi3, the spec, does not understand 'null' so that makes working with other tools taking in openapi3 a bit hard

handle nullable: true types

---

src/core/jsonSchema.ts

Hi @horiuchi 
Thank you for the great tool
It's really useful!!
but I want one thing to be fixed
When you convert the path like (pet/owner/{id}), the path will be converted like this
petowner$Id
sometimes it’s difficult to read...
So, I want the path to be converted like below
petOwner$Id
This PR is for that :)

fix: typename when the path is nested

---

src/core/schemaConvertor.ts
test/simple_schema_test.ts
test/snapshots/json-schema-draft-04/apimeta/_expected.d.ts

Our use case is that we're generating a package with from the OpenAPI
and given `--namespace ''` the generated interfaces are declared and not
exported. We could specify a namespace instead and the namespace would
be declared and the interfaces exported, but then we would need to use
the `namespace.InterfaceName` syntax or use cumbersome imports like
`import InterfaceName = namespace.InterfaceName` or type definitions
like `type InterfaceName = namespace.InterfaceName` throught the code
base.
Right now, we can either add those imports/type definitions or we can
run `sed` on the generated TypeScript file to change `declare` to
`export` as a workaround.
So, when using with empty namespace, i.e. specifying `--namespace ''` on
the CLI the generated interfaces should be exported as well. This …

refactor: use `export` when given empty namespace

---

package-lock.json
package.json
src/core/dtsGenerator.ts
src/core/referenceResolver.ts
test/nested_allof_test.ts

Currently, **dtsGenerator** will ignore nested **allOf** keywords.
i.e. The Schema:
```
{
$id: '/test/nested/allOf',
$schema: 'http://json-schema.org/draft-07/schema#',
type: 'object',
allOf: [ {
type: 'object',
properties: { a: { type: 'string' } }
}, {
type: 'object',
allOf: [
{
type: 'object',
properties: { b: { type: 'string' } }
},
{
type: 'object',
properties: { c: { type: 'string' } }
}
]
} ],
required: ['a', 'b', 'c']
}
```
Will only generate:
```
declare namespace Test {
namespace Nested {
export interface AllOf {
a: string;
// Missing 'b', 'c' properties.
}
}
}
```
This commit adds changes to recursively scan for nested **allOf** keywords within the schema, and generate the properties associated with the nested elements.
The mocha unit test:
```
test/nested_allof_test.ts
```
Is …

Handle nested schema 'allOf' keywords.

---

src/core/jsonSchema.ts
test/snapshots/openapi-v3/empty_response/_expected.d.ts
test/snapshots/openapi-v3/empty_response/empty_response.yaml

Since there was no "content" or "$ref", it didnt register as part of the schema which caused it to be unable to find the key. This PR assigns an empty object to the key.
This should of been caught by the test unit but the test unit contained an invalid configuration so it didnt catch anything at all. I fixed that too
Resolves the issue in the comment of https://github.com/horiuchi/dtsgenerator/issues/330#issuecomment-627499356 (that comment, not the issue, thats for something else)

Fixes ref to empty response causing an error (Error: test The $ref tarrgets root is not found: #/components/responses/created)

---

src/core/dtsGenerator.ts
test/snapshots/openapi-v3/nullable/_expected.d.ts
test/snapshots/openapi-v3/nullable/nullable.yaml

In the current version, when a schema has `anyOf` and `nullable: true`, it does not work as expected.
The expected behaviour is that the `null` type is appended, like the current behaviour for a `type` array.

Add support for nullable anyOf in OpenApi v3

---

src/core/utils.ts

I ran into a bug and I believe it has to do with a missing truthy check.
```
TypeError: Cannot use 'in' operator to search for '$ref' in null
at mergeSchema (/usr/local/lib/node_modules/dtsgenerator/dist/core/utils.js:47:31)
at /usr/local/lib/node_modules/dtsgenerator/dist/core/utils.js:60:22
at Array.forEach (<anonymous>)
at mergeSchema (/usr/local/lib/node_modules/dtsgenerator/dist/core/utils.js:50:20)
at /usr/local/lib/node_modules/dtsgenerator/dist/core/utils.js:60:22
at Array.forEach (<anonymous>)
at mergeSchema (/usr/local/lib/node_modules/dtsgenerator/dist/core/utils.js:50:20)
at /usr/local/lib/node_modules/dtsgenerator/dist/core/utils.js:60:22
at Array.forEach (<anonymous>)
at Object.mergeSchema (/usr/local/lib/node_modules/dtsgenerator/dist/core/utils.js:50:20)
```
I checked the …

fix(mergeSchema): add truthy check for value

---

src/core/dtsGenerator.ts
test/nested_oneof_test.ts

fix: nested `oneOf` & `anyOf` keywords

---

src/core/jsonSchema.ts
test/snapshots/openapi-v3/support-media-type/_expected.d.ts
test/snapshots/openapi-v3/support-media-type/example.yaml

Without this, the following media types are not accepted:
- application/vnd.github+json
- application/vnd.github.v3+json
- application/vnd.github.v3.raw+json
- application/vnd.github.v3.text+json
- application/vnd.github.v3.html+json
- application/vnd.github.v3.full+json

Support vendor media types (allow periods in application/*+json)

---

src/core/referenceResolver.ts
src/core/type.ts

The `ReferenceResolver::getAllRegisteredIdAndSchema` return type and by extension the `PluginContext::inputSchemas` type are `Iterators` which means they cannot be used in `for..of` or `Array::from`. This makes writing plugins a little more clunky than is ideal.
As `Map::entries` returns an `IterableIterator` (which can be used in the aforementioned contexts) we could use that type for the above function/fields and make them easier to work with.

feat: make PluginContext::inputSchemas an IterableIterator

---

SupportedFeatures.md
src/core/jsonSchema.ts
test/snapshots/openapi-v3/support-media-type/_expected.d.ts
test/snapshots/openapi-v3/support-media-type/example.yaml

I'm working with an API that sends mobile wallet passes, and `dtsgenerator` throws an error on that part of the schema. This adds support for `application/vnd.apple.pkpass` (Apple Pay) and `application/jwt` (Google Pay, among other uses). Both are typed as strings.

feat: support mobile wallet media types

---

src/utils.ts
test/utils_test.ts

Hi @horiuchi!
While trying to generate types for a remote swagger spec, I ran into a small bug.
I was using this configuration file:
```
{
"input": {
"urls": ["https://example.com/swagger.json"]
},
"outputFile": "example.d.ts"
}
```
and I ran the command:
```
dtsgen -c dtsgen.json
```
I noticed that `stdin` was always set to `true`, because its value is always determined by the command line options, and it does not look at possible `files` and `urls` options from the config file.
This PR updates the logic just a little, so it takes the value from the command line if it is there, and otherwise looks at the determined `files` and `urls` arrays.

Fix handling of stdin option

---

src/core/astBuilder.ts

This PR removes the use of the `decorators` parameter that was deprecated in v4.8.0 of TypeScript.
The runtime warning that was showed before this change is:
> DeprecationWarning: 'createInterfaceDeclaration' has been deprecated since v4.8.0. Decorators are no longer supported for this function. Callers should switch to an overload that does not accept a 'decorators' parameter. 
Signed-off-by: Matteo Collina <hello@matteocollina.com>

Remove deprecated decorators parameter

---

src/core/jsonSchema.ts

some [Specs](https://dataaccess.scania.com/rfms4/swagger/v4.0.0/swagger.json) ( ![](https://validator.swagger.io/validator?url=https%3A%2F%2Fdataaccess.scania.com%2Frfms4%2Fswagger%2Fv4.0.0%2Fswagger.json) ) include compound media type values, such as: `"application/json; rfms=vehiclestatuses.v4.0; scania=vehiclestatuses.v1":`
API treats this as `application/json`. Follow up values are indicator for API to return extra information.
This fix allows "application/json" media type to accept follow-up values

support for <application/json; ....> media types
